const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const dealershipSchema = new Schema({ // ID automatically generated by mongoose
    created_at: Date,
    updated_at: Date,
    make: {
        type: String,
        required: true
    },
    city: {
        type: String,
        required: true
    },
    province: {
        type: String,
        required: true
    },
    postal_code: {
        type: String,
        required: true
    },
    street: {
        type: String,
        required: true
    }
});

// allows every Dealership to have created and updated dealership automatically
dealershipSchema.pre('save', function(next){ 
    const currentDate = new Date ();

    this.updated_at = currentDate;

    if(!this.created_at) {
        this.created_at = currentDate;
    }
    next();
});

const Dealership = mongoose.model('Dealership', dealershipSchema);

module.exports = Dealership;